baseURL = "http://this.lu"

title = "Donglua"
languageCode = "zh-CN"

theme="hugo-octopress"


[taxonomies]
  category = "categories"
  tag = "tags"


[params]
  description = "Stop Stopping"
  author = "东东鲁"
  colorscheme = "white"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"






