baseURL = "http://donglua.github.io"

title = "Donglua"
languageCode = "zh-CN"

theme="hugo-octopress"


[taxonomies]
  category = "categories"
  tag = "tags"


[params]
  description = "Stop Stopping"
  defaultDescription = "Stop Stopping"

  author = "Donglua"
  colorscheme = "white"
  github = "//www.github.com/donglua"
  continueReadingText = "阅读全文"
  rss = true  # switch to true to enable RSS icon link

  pygmentsuseclasses = false
  pygmentsstyle = "solarized_dark"

  disqusShortname = "thislu"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"

[blackfriday]
  hrefTargetBlank = true # open the external links in a new window
  fractions = false





